Homework 2: added basic GitHub and StackOverflow clients; added scheduler stub.
unters/java-course-tinkoff-pt2 pull request #2
Opened 2024-02-25 20:52 UTC by unters

Привет, здорово, что ты снова мой проверяющий)

На момент публикации PR в нем отсутствуют WireMock тесты, а также (вопреки названию PR) клиент для StackOverflow. С WireMock'ом возникли технические сложности - тесты будут, - а со StackOverflow я пока просто не разбирался - с взаимодействием с Api через `WebClient` и `HttpExchange` я познакомился на примере GitHub'а, и прикрутить аналогичный клиент для StackOverflow не составит труда.

В этом семестре я немного подзапоздал со сдачей ДЗ, однако на следующей неделе рассчитываю наверстать отставание: 
 * Во-первых, в ближайшие два-три дня запушу тесты для scrapper'a, расширю функционал `GitHubClient`'а и сделаю клиент для StackOverflow.
 * Во-вторых, разберусь с первым ДЗ -  мне не хочется пользоваться предложенной библиотекой для взаимодействия с TelegramBotApi, и я решил переделать всё на вебхуках. Это решение отчасти является причиной, почему я не ответил на замечании по первому PR. Под это будет новый PR - я тебе о нем сообщу. Большая часть работ по вебхукам уже сделана.

Как только я разберусь с перечисленным, очень постараюсь сдавать задания заранее и сразу в полном объеме.

2024-02-26 18:16 UTC, SHvatov requested changes
@unters оставил комментарии, посмотри их, пожалуйста. На будущее - я все понимаю, но в следующие разы я буду снижать баллы, если после дедлайна задание сдано не полностью.

2024-02-26 18:16 UTC, SHvatov commented on scrapper/src/main/java/edu/scrapper/dto/github/PullRequestCommentTo.java
> +    public PullRequestCommentTo(
`@RequiredArgsConstructor` + `JsonProperty` на полях, jackson такое умеет делать.

2024-02-26 18:16 UTC, SHvatov commented on scrapper/src/main/java/edu/scrapper/service/client/GitHubClient.java
> +public interface GitHubClient {
лайк за использование этой шутки)

2024-03-03 07:36 UTC, unters commented on scrapper/src/main/java/edu/scrapper/dto/github/PullRequestCommentTo.java
> +    public PullRequestCommentTo(
Спасибо. В конечнои итоге решил обойтись record'ом (хотя мне не очень нравится, что геттеры не имеют в нем префикса get) и `@JsonNaming`'ом.

2024-03-03 15:45 UTC, unters commented
**Делаю merge, чтобы можно было доделать задание 3. Если понадобятся правки по этому pr'у, то сделаю их в отдельном pr'е.**

2024-03-03 15:45 UTC, merged

2024-03-03 18:24 UTC, SHvatov reviewed
@unters 👌, но на будущее - можно иметь изменения из ветки не мержа ее при этом в мастер. Достаточно сделать от нее чекаут, или же запуллить ее себе в рабочую ветку.

2024-03-03 18:24 UTC, SHvatov commented
А, и не видно все еще покрытия - поправь плиз.